steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - services/api/Dockerfile
      - -t
      - $_AR_IMAGE
      - .
images:
  - $_AR_IMAGE
options:
  logging: CLOUD_LOGGING_ONLY
